name: basketball_coach
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  camera: ^0.11.0+2
  path_provider: ^2.0.11
  image: ^4.0.21
  http_parser: ^4.1.2
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
